name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - run: npm ci
      - run: cp .env.example .env
      - run: npm run lint
      - run: npm run build
      - run: npm test
      - run: npm run node &
      - run: npm run deploy

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          directory: ./coverage
          name: codecov-umbrella
          fail_ci_if_error: true
          flags: unittests

      - name: Run Slither
        uses: crytic/slither-action@v0.1.1
        continue-on-error: true
        id: slither
        with:
          sarif: results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
